name: CMake Multi-Platform Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libsdl2-dev python3-pip
        pip install pcpp

    - name: Setup LVGL configuration
      run: |
        cp LvglPlatform/lvgl/lv_conf_template.h LvglPlatform/lvgl/lv_conf.h
        sed -i 's/#define LV_COLOR_DEPTH 32/#define LV_COLOR_DEPTH 16/' LvglPlatform/lvgl/lv_conf.h
        sed -i 's/#if 0/#if 1/' LvglPlatform/lvgl/lv_conf.h  
        
        sed -i 's|#include LV_CONF_PATH|#include "../lv_conf.h"|' LvglPlatform/lvgl/src/lv_conf_internal.h

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DLV_CONF_INCLUDE_SIMPLE=1

    - name: Build
      run: |
        cd build
        cmake --build . --config Release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: my_app
        path: build/my_app